#!/usr/bin/env bash
set -e

username=$1

if [ -n "$username" ]; then
  ## Verify that argument is a valid user
  id "$username" >/dev/null
else
  ## Default to the calling user
  username=$USER
fi

authorized_keys="/home/$username/.ssh/authorized_keys.d/github"
etag_file="/home/$username/.ssh/.github-ssh-keys.etag"

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' exit

curl --silent --fail-with-body --output "$tmpfile"\
  --etag-save "$etag_file" --etag-compare "$etag_file" \
  --write-out '%{stderr}%{method} %{url} %{http_code} (%header{etag})\n'\
  "https://api.github.com/users/$username/keys"

## Only update authorized_keys file if the API call returned content
if [ $(stat --printf '%s' "$tmpfile") -gt 0 ]; then 
  echo "Updating $authorized_keys from github account $username" >&2
  
  mkdir -p "/home/$username/.ssh/authorized_keys.d"
  jq --raw-output "map(\"\\(.key) $username\\(.id)@github.com\")[]" <"$tmpfile" | tee "$authorized_keys"

  chmod 0700 "/home/$username/.ssh/authorized_keys.d"
  chmod 0600 "$authorized_keys"
else
  echo "$authorized_keys is up to date with github account $username" >&2
fi
